### ISSUE TITLE
Warning with ruby 2.7

### ISSUE THREAD

**Issue by joerggollnick** [ddfreyne/cri#107]
Running nanoc with ruby 2.7 (on ArchLinux) gives following warning as there was a "breaking" change in ruby.

/usr/lib/ruby/gems/2.7.0/gems/cri-2.15.9/lib/cri/command_dsl.rb:243: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/gems/2.7.0/gems/cri-2.15.9/lib/cri/command_dsl.rb:155: warning: The called method `option' is defined here

**Comment by joerggollnick** [comment]
Change was announced here:

https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by ddfreyne** [comment]
This is fixed in 9a3d810.

**Comment by ddfreyne** [comment]
And released as 2.15.10!
