### ISSUE TITLE
Allow `--help --verbose`

### ISSUE THREAD

**Issue by ddfreyne** [ddfreyne/cri#33]
Currently, `--help --verbose` does not print the help verbosely, because both options are independent and do not know about each other.

Not sure how to solve this.

**Comment by opensourcegrrrl** [comment]
Alternative solution is to write the five extra commands and eliminate the need for --verbose.

**Comment by ddfreyne** [comment]
I’m assuming you mean the five extra commands from nanoc. They’re hidden on purpose; they’re deprecated so they shouldn’t be shown by default.

**Comment by opensourcegrrrl** [comment]
Is there confusion in removing the line `(5 hidden commands omitted; show them with --verbose)`.

If they are deprecated, why do I need to know about them. Migration information could go into a migration guide or an upgrade guide.

**Comment by ddfreyne** [comment]
> Is there confusion in removing the line `(5 hidden commands omitted; show them with --verbose)`.

That is possible, but it doesn’t solve the problem that `--help --verbose` doesn’t work as expected, though.

> If they are deprecated, why do I need to know about them.

That’s why they’re hidden. Perhaps the message could be updated to say that they are deprecated.

**Comment by opensourcegrrrl** [comment]
I personally would rather not see them at all. That said, I am not upgrading from one version to another at the moment. When I do, I will first check the Upgrade guide rather than the list of commands.

**Comment by ddfreyne** [comment]
They won’t be removed from nanoc 3.x because nanoc follows semantic versioning.

**Comment by opensourcegrrrl** [comment]
+1 for that rationale.

**Comment by ddfreyne** [comment]
Closing, as I don’t believe that there is any reasonable way that `--help --verbose` can print the help verbosely. Cri handles the options in a certain order; `--help` being evaluated after `--verbose` is odd (and what about other cases, such as `--help --version`?).

`help --verbose` will still work.
