### ISSUE TITLE
Program exiting after wrong command or option - Decision should be taken by program instead of CRI

### ISSUE THREAD

**Issue by aseemjakhar** [ddfreyne/cri#49]
While testing I found that if we specify a wrong command or option the CRI code calls exit(). Shouldn't that decision be taken by the program instead of CRI. I am planning to use CRI for a my application that needs a command loop and cant afford to exit on wrong input. Right now Im overriding the exit method to avoid program termination, but I dont think that is an elegant workaround

**Comment by ddfreyne** [comment]
Agreed! Perhaps being able to provide a callback when an unrecognised command or option is provided is a good approach (and can be backwards-compatible that way, too).

**Comment by ddfreyne** [comment]
Potential fix in #51.
