### ISSUE TITLE
Run block executes even if --help option is specified

### ISSUE THREAD

**Issue by aseemjakhar** [ddfreyne/cri#50]
Help flag takes a block and then we have a run block which executes the command. If the command has --help option specified, the help block executes and then the run block also executes. Ideally if help option is specified then run block should not execute. 
Again, coming from my application which is using Cri in a command loop. I cannot exit in the help block and have no control in Cri to stop execution of run block. Currently Im checking the presence of help option inside run block and just return if it is present.

**Comment by ddfreyne** [comment]
#51 also takes care of this.
