### ISSUE TITLE
Invalid syntax in command.rb

### ISSUE THREAD

**Issue by mmerfort** [ddfreyne/cri#60]
/usr/local/share/gems/gems/r10k-2.6.0.dev/lib/r10k/cli.rb:9:in `command': /usr/local/share/gems/gems/cri-2.9.1/lib/cri/command.rb:46: syntax error, unexpected ')' (SyntaxError)

```ruby
def initialize(is_error:)
```

**Comment by ddfreyne** [comment]
This syntax is valid in Ruby 2.0+.

Ruby 1.9.x, 2.0.x and 2.1.x are no longer supported. Cri requires Ruby 2.1+.

**Comment by ddfreyne** [comment]
I’ve updated the gemspec to specify that Cri requires Ruby 2.1 or higher (see ae8e276), so this error will no longer happen the way it did.

Thank you for reporting!
