### ISSUE TITLE
Display help for sub-commands that require an argument?

### ISSUE THREAD

**Issue by rchady** [ddfreyne/cri#76]
Is it possible to make sub-commands accept -h even if the wrong number of arguments to it are provided?  Right now I just get the wrong number of arguments, but -h/--help should be there to help them find out what arguments are needed I would think?

**Comment by ddfreyne** [comment]
I think `-h` should work even if the wrong number of arguments is given — maybe options need to be evaluated before validating arguments.

**Comment by ddfreyne** [comment]
This is fixed in #78.

**Comment by ddfreyne** [comment]
… and is now released in Cri 2.15.1!
