### ISSUE TITLE
Cri::CommandRunner usage understanding

### ISSUE THREAD

**Issue by andkirby** [ddfreyne/cri#79]
Is there some extended example/documentation how to use Cri::CommandRunner? I want to build a command in a class.
It clear it will call `run`. But where arguments coming from? How this class can be loaded/declared?

Thanks in advance.

Kirby

**Comment by ddfreyne** [comment]
The command runner was indeed not well-documented, so I’ve extended the documentation: [The command runner](https://github.com/ddfreyne/cri#the-command-runner).

**Comment by ddfreyne** [comment]
I’ll close this issue now, but feel free to reopen if needed!

**Comment by andkirby** [comment]
Thank you, @ddfreyne!
