### ISSUE TITLE
Feature: Arbitrary arguments

### ISSUE THREAD

**Issue by roberts1000** [ddfreyne/cri#82]
The README explains how to pass arguments to the command https://github.com/ddfreyne/cri#argument-parsing using `param`, but it looks like we have to name each argument.  Is it possible to have a command accept multiple arguments? I'd like to be able to do something like

```
my_command arg1 arg2 argN
```

**Comment by ddfreyne** [comment]
This is currently supported when no `param` or `no_params` is explicitly specified. For example:

```
name        'set'
usage       'set key=value ...'
summary     'set config values'
description '…'

run do |opts, args|
  puts "Printing args:"
  args.each { |arg| p arg }
end
```ruby

```
% ./sample a b c d
Printing args:
a
b
c
d
```

After the introduction of argument parsing (using `param` and `no_param`), it indeed became somewhat unclear how to handle arbitrary arguments. I’ll update the documentation to clarify.

**Comment by ddfreyne** [comment]
I’ve added a section [Allowing arbitrary arguments](https://github.com/ddfreyne/cri#allowing-arbitrary-arguments) to the README, which should make this more clear.

Thanks for reporting!

**Comment by roberts1000** [comment]
Thank you for clearing this up and enhancing the README!
