### ISSUE TITLE
Is the argument: option required when using multiple: true

### ISSUE THREAD

**Issue by roberts1000** [ddfreyne/cri#83]
I'm trying to use multiple arguments and I have a `option` block that looks like this:

```ruby
option :g, :groups, "specify the groups", argument: :required, multiple: true do |value, cmd|
  puts value
end
```

It works fine if `argument: :required` or `argument: optional` is present.  If I remove that, `value` is just an array of `true` elements.  Should `argument:` be present when using `multiple:` or is this a bug?  I couldn't figure it out from the docs.

**Comment by ddfreyne** [comment]
`option`’s `argument:` parameter defaults to `:forbidden`.

When an option has a forbidden argument, its value will end up being `true`. This is intended for flags such as `--verbose`:

```ruby
flag '-v', '--verbose', 'be verbose'
```

```ruby
# assuming the command is invoked with --verbose:

p options[:verbose]
# => true
```

When using `multiple: true`, all option values end up in an array. For options with required arguments, this means the array ends up containing a list of strings, while for options with forbidden arguments, the array ends up containing a list of `true`s:

```ruby
flag '-v', '--verbose', 'be verbose'
```

```ruby
# assuming the command is invoked with --verbose --verbose --verbose:

p options[:verbose]
# => [true, true, true]
```

The documentation is admittedly unclear on `:forbidden` being the default, and on the array of `true`s. Will update.

**Comment by ddfreyne** [comment]
Hi,

I’ve greatly expanded the [section on how to define command-line options](https://github.com/ddfreyne/cri#command-line-options). It now has an explicit section on `argument:`, and also comes with a handful of examples. This should make it more understandable.

Let me know what you think!

**Comment by roberts1000** [comment]
This is a great improvement and a big help!  Thank you taking the time to improve the docs.
