### ISSUE TITLE
colored breaks awesome_print

### ISSUE THREAD

**Issue by roberts1000** [ddfreyne/cri#89]
Great gem! I've been using `cri` on a couple projects and it's been working great.  A user reported a bug on my rspec_n gem (which uses `cri`) and stated rspec_n [breaks awesome_print](https://github.com/roberts1000/rspec_n/issues/35) when both gems are listed in a `Gemfile`. I traced the issue back to the `colored` gem that `cri` uses and thought I would make sure you were aware (especially since awesome_print is such a popular gem).

`colored` adds `colorize`, `green`, `red`, etc... methods [directly on String](https://github.com/defunkt/colored/blob/v1.2/lib/colored.rb#L36).  `awesome_print` [does the same thing](https://github.com/awesome-print/awesome_print/blob/v1.8.0/lib/awesome_print/core_ext/string.rb#L6).  The gem that gets listed last in a Gemfile has their implementation loaded by Bundler.  If `colored` is listed last, it breaks `awesome_print`.

Based on [this comment](https://github.com/awesome-print/awesome_print/blob/v1.8.0/lib/awesome_print/colorize.rb#L14) in the `awesome_print` code, awesome_print seems to have compatibility with the [colorize](https://github.com/fazibear/colorize) gem (an alternative to colored), but it doesn't seem to know about [colored](https://github.com/defunkt/colored).

**Comment by ddfreyne** [comment]
Here’s a potential fix: #90.

I argue that coloring text and making it bold is simple enough that it does not require a separate gem.

**Comment by ddfreyne** [comment]
This is now fixed and released in Cri 2.15.4.

**Comment by roberts1000** [comment]
Thanks for the quick fix!
