### ISSUE TITLE
Version 2.15.7 causes runtime error

### ISSUE THREAD

**Issue by hawkeye-7** [ddfreyne/cri#98]
r10k: Runtime error: #<ArgumentError: R10K::Action::Puppetfile::Install cannot handle option 'help'>
Error while running: #<RuntimeError: r10k could not install all required modules>

**Comment by ddfreyne** [comment]
I didn’t manage to track this down, though I believe it should be fixed in a more recent version of Cri (at least 2.15.8, preferably 2.15.10).

Can you verify that this problem is gone?

I’ll close the issue for now, but let me know if it’s still present.
